<?php

namespace Bangnation\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TurnOnsOffsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnOnsOffsRepository extends EntityRepository
{
}
