parameters:
    database_driver:   pdo_mysql
    database_host:     mysql.bangnation.net
    database_port:     ~
    database_name:     bangnation_db
    database_user:     bangnation_user
    database_password: s0m3r3d@shoe

    mailer_transport:  smtp
    mailer_host:       mail.bangnation.net
    mailer_user:       no-reply@bangnation.net
    mailer_password:   ^eTur2sA

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    node: /usr/bin/node
    node_paths: [/usr/lib/node_modules]
#    node: /usr/local/bin/node
#    node_paths: [/usr/local/lib/node_modules]