# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
_welcome:
    resource: "@BangnationCommonBundle/Controller/WelcomeController.php"
    type:     annotation
    prefix:   /
    
about:
    resource: "@BangnationCommonBundle/Controller/AboutController.php"
    type:     annotation
    prefix:   /
    
contact:
    resource: "@BangnationCommonBundle/Controller/ContactController.php"
    type:     annotation
    prefix:   /
    
privacy:
    resource: "@BangnationCommonBundle/Controller/PrivacyController.php"
    type:     annotation
    prefix:   /
    
terms:
    resource: "@BangnationCommonBundle/Controller/TermsController.php"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile